title: "Khans' blog"
author: "Mahdi Khan"
email: 70070156+mhnkhan@users.noreply.github.com
description: "Mahdi Khans' testing blog on GH-Pages. Checkout cool new bugs & typos! :-D LOL"
	# this means to ignore newlines until "baseurl:"
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mhnkhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
